version: 2
updates:
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: develop
  ignore:
  - dependency-name: github.com/onsi/ginkgo
    versions:
    - 1.15.1
    - 1.15.2
    - 1.16.0
    - 1.16.1
  - dependency-name: github.com/gonvenience/neat
    versions:
    - 1.3.6
  - dependency-name: github.com/gonvenience/ytbx
    versions:
    - 1.3.1
    - 1.4.0
  - dependency-name: github.com/gonvenience/bunt
    versions:
    - 1.3.2
  - dependency-name: github.com/spf13/cobra
    versions:
    - 1.1.2
