---
name: Tests

on:
  push:
    tags-ignore:
      - '**'
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19.x

    - name: Check out code into the Go module directory
      uses: actions/checkout@v3

    - run: go build ./...

    - name: Run Go Unit Tests
      run: |
        go get -t github.com/onsi/ginkgo/v2/ginkgo/...@$(grep github.com/onsi/ginkgo/v2 go.mod | awk '{ print $2 }')
        go run github.com/onsi/ginkgo/v2/ginkgo \
          --coverprofile=unit.coverprofile \
          --randomize-all \
          --randomize-suites \
          --fail-on-pending \
          --keep-going \
          --slow-spec-threshold=4m \
          --compilers=2 \
          --race \
          --trace \
          --flake-attempts=3 \
          ./...

    - name: Upload Code Coverage Profile
      uses: codecov/codecov-action@v1
      with:
        files: ./*.coverprofile
        flags: unittests
        fail_ci_if_error: true
        verbose: false
